synchronize:
  paths:
    - source: .
      exclude:
        - "qwerty.md"

pretranslate:
  segments:
    ignore_frontmatter_keys:
    - "layout"
    - "permalink"
    - "noindex"
    - "date"
    - "override"
    - "codelabs"
    - "tags"
    - "authors"
    ignore_patterns:
    - !ruby/regexp /{%\s?([a-zA-Z0-9\.\,\-\?\'\"\s]*)\s?%}/    
  paths:
  - source: .
    include:
    - "pretrans5/*.*"

settings:
  ignore_escaped_strings: true
  frontmatter_not_escaped: true
