synchronize:
  paths:
    - source: .
      exclude:
        - "qwerty.md"

pretranslate:
    - source: .
      include:
        - "README.md"
        - "config/*"
settings:
  ignore_escaped_strings: true
